---
title: "GETurbineCaseStudyPart1"
output: html_document
---

__Read the data first__

```{r}

filenameToRead<-"train.csv"
turbineTrainData<-read.csv(filenameToRead)
str(turbineTrainData)

```


__Performing some data explorations__

```{r}
#Find the summary of the values

summary(turbineTrainData$X189)

summary(turbineTrainData$X190)

```
The summary clearly shows that the X190 and X189 have similar distribution

Now drawing the box plts to see the disribution

```{r}
#boxplots

boxplot(turbineTrainData$X189,turbineTrainData$X190,names=c("turbine 189","turbine 190"),main="Box Plots comparing turbine 189 & 190")

abline(a=median(turbineTrainData$X189),b=0,col="red",lty=2)

#boxplot is showing that the distribution of the datapoints in the quantiles is similar. The median is almost the same which indicates that X189 can be a good distribution for making predictions for X190

#inter quartile ranges
IQR(turbineTrainData$X189, na.rm = FALSE, type = 7)
IQR(turbineTrainData$X190, na.rm = FALSE, type = 7)
```

Now drawing the histogram
```{r}
#hist
par(mfrow=c(2,2))
hist(turbineTrainData$X189,main="Histogram for turbine189",xlab ='Power Values for 189')
density189<-density(turbineTrainData$X189)
plot(density189, main="Density for turbine189",xlab ='Power Values for 189')
polygon(density189, col="red", border="blue")

hist(turbineTrainData$X190,main="Histogram for turbine190",xlab ='Power Values for 190')
density190<-density(turbineTrainData$X190)
plot(density190, main="Density for turbine190",xlab ='Power Values for 190')
polygon(density190, col="red", border="blue")

```




